# Generated by Django 4.2.4 on 2023-09-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_lbs', models.IntegerField()),
                ('size_kgs', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
