# Generated by Django 4.2.4 on 2023-09-29 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.weight'),
            preserve_default=False,
        ),
    ]
