# Generated by Django 4.2.4 on 2023-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_workout_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weight',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.AddField(
            model_name='workout',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
            preserve_default=False,
        ),
    ]
