# Generated by Django 4.2.4 on 2023-10-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customer_remove_workout_weight_delete_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_lbs', models.IntegerField()),
            ],
        ),
    ]
