# Generated by Django 4.2.4 on 2023-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weights',
            field=models.ManyToManyField(to='main_app.weight'),
        ),
    ]
